
name: Recruit Monitor
on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install libs
        run: python -m pip install -r requirements.txt
      - name: Run monitor
        env:
          GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
          SPREADSHEET_ID:  ${{ secrets.SPREADSHEET_ID }}
          WORKSHEET_NAME:  ${{ secrets.WORKSHEET_NAME }}
        run: python monitor.py
